apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-1
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/grafana"
