{
 "title": "Pod Status Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "OOMKilled Containers",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\",pod!=\"\",container!=\"POD\"}) by (pod)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Container Restart Rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "increase((kube_pod_container_status_restarts_total{pod!=\"\",container!=\"POD\"}[5m])) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Error Status POD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_last_terminated_reason{reason=\"Error\",pod!=\"\",container!=\"POD\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Failed Status of POD",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase=\"Failed\"}"
    }
   ]
  }
 ]
}